-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.auth_token_pairs
(
    session_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    access_token character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    refresh_token character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    access_expires_at timestamp without time zone NOT NULL,
    refresh_expires_at timestamp without time zone NOT NULL,
    user_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_activity timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT auth_token_pairs_pkey PRIMARY KEY (session_id)
);

CREATE TABLE IF NOT EXISTS public.auth_user_sessions
(
    session_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ip_address character varying(45) COLLATE pg_catalog."default",
    user_agent text COLLATE pg_catalog."default",
    last_activity timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active boolean NOT NULL DEFAULT true,
    login_time timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    logout_time timestamp without time zone,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT auth_user_sessions_pkey PRIMARY KEY (session_id)
);

CREATE TABLE IF NOT EXISTS public.dish_recipe_standards
(
    recipe_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    dish_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ingredient_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    unit character varying(50) COLLATE pg_catalog."default" NOT NULL,
    quantity_per_serving numeric(10, 4) NOT NULL,
    notes text COLLATE pg_catalog."default",
    cost numeric(15, 2),
    updated_by_user_id character varying(50) COLLATE pg_catalog."default",
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    kitchen_id character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT dish_recipe_standards_pkey PRIMARY KEY (recipe_id),
    CONSTRAINT unique_dish_kitchen_ingredient UNIQUE (dish_id, kitchen_id, ingredient_id)
);

CREATE TABLE IF NOT EXISTS public.ingredient_types
(
    ingredient_type_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ingredient_type_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    active boolean NOT NULL DEFAULT true,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ingredient_types_pkey PRIMARY KEY (ingredient_type_id),
    CONSTRAINT ingredient_types_name_key UNIQUE (ingredient_type_name)
);

CREATE TABLE IF NOT EXISTS public.inventory_adjustment_details
(
    adjustment_detail_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    adjustment_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ingredient_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    quantity_before numeric(15, 4) NOT NULL,
    quantity_after numeric(15, 4) NOT NULL,
    quantity_difference numeric(15, 4) NOT NULL,
    unit character varying(50) COLLATE pg_catalog."default" NOT NULL,
    unit_cost numeric(15, 2),
    total_value numeric(15, 2),
    reason text COLLATE pg_catalog."default",
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT inventory_adjustment_details_pkey PRIMARY KEY (adjustment_detail_id)
);

CREATE TABLE IF NOT EXISTS public.inventory_adjustments
(
    adjustment_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    kitchen_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    adjustment_date date NOT NULL,
    adjustment_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    reason text COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'draft'::character varying,
    total_value numeric(15, 2),
    approved_by_user_id character varying(50) COLLATE pg_catalog."default",
    approved_date timestamp without time zone,
    created_by_user_id character varying(50) COLLATE pg_catalog."default",
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT inventory_adjustments_pkey PRIMARY KEY (adjustment_id)
);

CREATE TABLE IF NOT EXISTS public.inventory_export_details
(
    export_detail_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    export_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ingredient_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    quantity numeric(15, 4) NOT NULL,
    unit character varying(50) COLLATE pg_catalog."default" NOT NULL,
    unit_cost numeric(15, 2),
    total_cost numeric(15, 2),
    batch_number character varying(100) COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT inventory_export_details_pkey PRIMARY KEY (export_detail_id)
);

CREATE TABLE IF NOT EXISTS public.inventory_exports
(
    export_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    kitchen_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    export_date date NOT NULL,
    export_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    destination_kitchen_id character varying(50) COLLATE pg_catalog."default",
    order_id character varying(50) COLLATE pg_catalog."default",
    total_amount numeric(15, 2) DEFAULT 0,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'draft'::character varying,
    notes text COLLATE pg_catalog."default",
    issued_by_user_id character varying(50) COLLATE pg_catalog."default",
    approved_by_user_id character varying(50) COLLATE pg_catalog."default",
    approved_date timestamp without time zone,
    created_by_user_id character varying(50) COLLATE pg_catalog."default",
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT inventory_exports_pkey PRIMARY KEY (export_id)
);

CREATE TABLE IF NOT EXISTS public.inventory_import_details
(
    import_detail_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    import_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ingredient_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    quantity numeric(15, 4) NOT NULL,
    unit character varying(50) COLLATE pg_catalog."default" NOT NULL,
    unit_price numeric(15, 2) NOT NULL,
    total_price numeric(15, 2) NOT NULL,
    expiry_date date,
    batch_number character varying(100) COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    supplier_id character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT inventory_import_details_pkey PRIMARY KEY (import_detail_id)
);

CREATE TABLE IF NOT EXISTS public.inventory_imports
(
    import_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    kitchen_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    import_date date NOT NULL,
    order_id character varying(50) COLLATE pg_catalog."default",
    supplier_id character varying(50) COLLATE pg_catalog."default",
    total_amount numeric(15, 2) DEFAULT 0,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'draft'::character varying,
    notes text COLLATE pg_catalog."default",
    received_by_user_id character varying(50) COLLATE pg_catalog."default",
    approved_by_user_id character varying(50) COLLATE pg_catalog."default",
    approved_date timestamp without time zone,
    created_by_user_id character varying(50) COLLATE pg_catalog."default",
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT inventory_imports_pkey PRIMARY KEY (import_id)
);

CREATE TABLE IF NOT EXISTS public.inventory_stocks
(
    stock_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    kitchen_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ingredient_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    quantity numeric(15, 4) NOT NULL DEFAULT 0,
    unit character varying(50) COLLATE pg_catalog."default" NOT NULL,
    min_stock_level numeric(15, 4),
    max_stock_level numeric(15, 4),
    last_updated timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT inventory_stocks_pkey PRIMARY KEY (stock_id),
    CONSTRAINT uq_kitchen_ingredient_stock UNIQUE (kitchen_id, ingredient_id)
);

CREATE TABLE IF NOT EXISTS public.inventory_transactions
(
    transaction_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    kitchen_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ingredient_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    transaction_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    transaction_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    quantity numeric(15, 4) NOT NULL,
    unit character varying(50) COLLATE pg_catalog."default" NOT NULL,
    quantity_before numeric(15, 4) NOT NULL,
    quantity_after numeric(15, 4) NOT NULL,
    reference_type character varying(50) COLLATE pg_catalog."default",
    reference_id character varying(50) COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    created_by_user_id character varying(50) COLLATE pg_catalog."default",
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT inventory_transactions_pkey PRIMARY KEY (transaction_id)
);

CREATE TABLE IF NOT EXISTS public.kitchen_favorite_suppliers
(
    favorite_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    kitchen_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    supplier_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    notes text COLLATE pg_catalog."default",
    display_order integer,
    created_by_user_id character varying(50) COLLATE pg_catalog."default",
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT kitchen_favorite_suppliers_pkey PRIMARY KEY (favorite_id),
    CONSTRAINT uq_kitchen_supplier_favorite UNIQUE (kitchen_id, supplier_id)
);

CREATE TABLE IF NOT EXISTS public.master_dishes
(
    dish_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    dish_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    cooking_method character varying(100) COLLATE pg_catalog."default",
    category character varying(100) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    active boolean NOT NULL DEFAULT true,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT master_dishes_pkey PRIMARY KEY (dish_id),
    CONSTRAINT master_dishes_dish_name_key UNIQUE (dish_name)
);

CREATE TABLE IF NOT EXISTS public.master_ingredients
(
    ingredient_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ingredient_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    ingredient_type_id character varying(50) COLLATE pg_catalog."default",
    properties character varying(100) COLLATE pg_catalog."default",
    material_group character varying(100) COLLATE pg_catalog."default",
    unit character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT master_ingredients_pkey PRIMARY KEY (ingredient_id),
    CONSTRAINT master_ingredients_ingredient_name_key UNIQUE (ingredient_name)
);

CREATE TABLE IF NOT EXISTS public.master_kitchens
(
    kitchen_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    kitchen_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    address text COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    active boolean NOT NULL DEFAULT true,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT master_kitchens_pkey PRIMARY KEY (kitchen_id)
);

CREATE TABLE IF NOT EXISTS public.master_suppliers
(
    supplier_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    supplier_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    zalo_link text COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    active boolean NOT NULL DEFAULT true,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT master_suppliers_pkey PRIMARY KEY (supplier_id)
);

CREATE TABLE IF NOT EXISTS public.master_users
(
    user_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    user_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(50) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    active boolean NOT NULL DEFAULT true,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT master_users_pkey PRIMARY KEY (user_id),
    CONSTRAINT master_users_user_name_key UNIQUE (user_name)
);

-- Join table for many-to-many relation between users and kitchens
CREATE TABLE IF NOT EXISTS public.user_kitchens
(
    user_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    kitchen_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_kitchens_pkey PRIMARY KEY (user_id, kitchen_id)
);

CREATE TABLE IF NOT EXISTS public.order_details
(
    order_detail_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    order_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    dish_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    portions integer NOT NULL,
    note text COLLATE pg_catalog."default",
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT order_details_pkey PRIMARY KEY (order_detail_id)
);

CREATE TABLE IF NOT EXISTS public.order_ingredient_suppliers
(
    order_ingredient_supplier_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    order_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ingredient_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    selected_supplier_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    selected_product_id integer NOT NULL,
    quantity numeric(15, 4) NOT NULL,
    unit character varying(50) COLLATE pg_catalog."default" NOT NULL,
    unit_price numeric(15, 2) NOT NULL,
    total_cost numeric(15, 2) NOT NULL,
    selection_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    selected_by_user_id character varying(50) COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT order_ingredient_suppliers_pkey PRIMARY KEY (order_ingredient_supplier_id),
    CONSTRAINT uq_order_ingredient_supplier UNIQUE (order_id, ingredient_id)
);

CREATE TABLE IF NOT EXISTS public.order_ingredients
(
    order_ingredient_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    order_detail_id integer NOT NULL,
    ingredient_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    quantity numeric(15, 4) NOT NULL,
    unit character varying(50) COLLATE pg_catalog."default" NOT NULL,
    standard_per_portion numeric(10, 4),
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT order_ingredients_pkey PRIMARY KEY (order_ingredient_id)
);

CREATE TABLE IF NOT EXISTS public.order_supplementary_foods
(
    supplementary_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    order_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ingredient_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    quantity numeric(15, 4) NOT NULL,
    unit character varying(50) COLLATE pg_catalog."default" NOT NULL,
    standard_per_portion numeric(10, 4),
    portions integer,
    note text COLLATE pg_catalog."default",
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT order_supplementary_foods_pkey PRIMARY KEY (supplementary_id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    order_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    kitchen_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    order_date date NOT NULL,
    note text COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Pending'::character varying,
    created_by_user_id character varying(50) COLLATE pg_catalog."default",
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.supplier_price_list
(
    product_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    product_name character varying(255) COLLATE pg_catalog."default",
    ingredient_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    classification character varying(100) COLLATE pg_catalog."default",
    supplier_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    manufacturer_name character varying(255) COLLATE pg_catalog."default",
    unit character varying(50) COLLATE pg_catalog."default",
    specification character varying(100) COLLATE pg_catalog."default",
    unit_price numeric(15, 2) NOT NULL,
    price_per_item numeric(15, 2),
    effective_from timestamp without time zone,
    effective_to timestamp without time zone,
    active boolean NOT NULL DEFAULT true,
    new_buying_price numeric(15, 2),
    promotion character(1) COLLATE pg_catalog."default",
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT supplier_price_list_pkey PRIMARY KEY (product_id)
);

ALTER TABLE IF EXISTS public.auth_token_pairs
    ADD CONSTRAINT fk_token_user FOREIGN KEY (user_id)
    REFERENCES public.master_users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_token_user
    ON public.auth_token_pairs(user_id);


ALTER TABLE IF EXISTS public.auth_user_sessions
    ADD CONSTRAINT fk_session_user FOREIGN KEY (user_id)
    REFERENCES public.master_users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_session_user
    ON public.auth_user_sessions(user_id);


ALTER TABLE IF EXISTS public.dish_recipe_standards
    ADD CONSTRAINT fk_recipe_dish FOREIGN KEY (dish_id)
    REFERENCES public.master_dishes (dish_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_recipe_dish
    ON public.dish_recipe_standards(dish_id);


ALTER TABLE IF EXISTS public.dish_recipe_standards
    ADD CONSTRAINT fk_recipe_ingredient FOREIGN KEY (ingredient_id)
    REFERENCES public.master_ingredients (ingredient_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_recipe_ingredient
    ON public.dish_recipe_standards(ingredient_id);


ALTER TABLE IF EXISTS public.dish_recipe_standards
    ADD CONSTRAINT fk_recipe_kitchen FOREIGN KEY (kitchen_id)
    REFERENCES public.master_kitchens (kitchen_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_recipe_kitchen
    ON public.dish_recipe_standards(kitchen_id);


ALTER TABLE IF EXISTS public.dish_recipe_standards
    ADD CONSTRAINT fk_recipe_user FOREIGN KEY (updated_by_user_id)
    REFERENCES public.master_users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.inventory_adjustment_details
    ADD CONSTRAINT fk_adjustment_detail_adjustment FOREIGN KEY (adjustment_id)
    REFERENCES public.inventory_adjustments (adjustment_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_adjustment_details_adjustment
    ON public.inventory_adjustment_details(adjustment_id);


ALTER TABLE IF EXISTS public.inventory_adjustment_details
    ADD CONSTRAINT fk_adjustment_detail_ingredient FOREIGN KEY (ingredient_id)
    REFERENCES public.master_ingredients (ingredient_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_adjustment_details_ingredient
    ON public.inventory_adjustment_details(ingredient_id);


ALTER TABLE IF EXISTS public.inventory_adjustments
    ADD CONSTRAINT fk_adjustment_approved_by FOREIGN KEY (approved_by_user_id)
    REFERENCES public.master_users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.inventory_adjustments
    ADD CONSTRAINT fk_adjustment_created_by FOREIGN KEY (created_by_user_id)
    REFERENCES public.master_users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.inventory_adjustments
    ADD CONSTRAINT fk_adjustment_kitchen FOREIGN KEY (kitchen_id)
    REFERENCES public.master_kitchens (kitchen_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_adjustments_kitchen
    ON public.inventory_adjustments(kitchen_id);


ALTER TABLE IF EXISTS public.inventory_export_details
    ADD CONSTRAINT fk_export_detail_export FOREIGN KEY (export_id)
    REFERENCES public.inventory_exports (export_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_export_details_export
    ON public.inventory_export_details(export_id);


ALTER TABLE IF EXISTS public.inventory_export_details
    ADD CONSTRAINT fk_export_detail_ingredient FOREIGN KEY (ingredient_id)
    REFERENCES public.master_ingredients (ingredient_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_export_details_ingredient
    ON public.inventory_export_details(ingredient_id);


ALTER TABLE IF EXISTS public.inventory_exports
    ADD CONSTRAINT fk_export_approved_by FOREIGN KEY (approved_by_user_id)
    REFERENCES public.master_users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.inventory_exports
    ADD CONSTRAINT fk_export_created_by FOREIGN KEY (created_by_user_id)
    REFERENCES public.master_users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.inventory_exports
    ADD CONSTRAINT fk_export_destination FOREIGN KEY (destination_kitchen_id)
    REFERENCES public.master_kitchens (kitchen_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.inventory_exports
    ADD CONSTRAINT fk_export_issued_by FOREIGN KEY (issued_by_user_id)
    REFERENCES public.master_users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.inventory_exports
    ADD CONSTRAINT fk_export_kitchen FOREIGN KEY (kitchen_id)
    REFERENCES public.master_kitchens (kitchen_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_exports_kitchen
    ON public.inventory_exports(kitchen_id);


ALTER TABLE IF EXISTS public.inventory_exports
    ADD CONSTRAINT fk_export_order FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_exports_order
    ON public.inventory_exports(order_id);


ALTER TABLE IF EXISTS public.inventory_import_details
    ADD CONSTRAINT fk_import_detail_import FOREIGN KEY (import_id)
    REFERENCES public.inventory_imports (import_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_import_details_import
    ON public.inventory_import_details(import_id);


ALTER TABLE IF EXISTS public.inventory_import_details
    ADD CONSTRAINT fk_import_detail_ingredient FOREIGN KEY (ingredient_id)
    REFERENCES public.master_ingredients (ingredient_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_import_details_ingredient
    ON public.inventory_import_details(ingredient_id);


ALTER TABLE IF EXISTS public.inventory_import_details
    ADD CONSTRAINT fk_import_detail_supplier FOREIGN KEY (supplier_id)
    REFERENCES public.master_suppliers (supplier_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_import_details_supplier
    ON public.inventory_import_details(supplier_id);


ALTER TABLE IF EXISTS public.inventory_imports
    ADD CONSTRAINT fk_import_approved_by FOREIGN KEY (approved_by_user_id)
    REFERENCES public.master_users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.inventory_imports
    ADD CONSTRAINT fk_import_created_by FOREIGN KEY (created_by_user_id)
    REFERENCES public.master_users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.inventory_imports
    ADD CONSTRAINT fk_import_kitchen FOREIGN KEY (kitchen_id)
    REFERENCES public.master_kitchens (kitchen_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_imports_kitchen
    ON public.inventory_imports(kitchen_id);


ALTER TABLE IF EXISTS public.inventory_imports
    ADD CONSTRAINT fk_import_order FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_imports_order
    ON public.inventory_imports(order_id);


ALTER TABLE IF EXISTS public.inventory_imports
    ADD CONSTRAINT fk_import_received_by FOREIGN KEY (received_by_user_id)
    REFERENCES public.master_users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.inventory_imports
    ADD CONSTRAINT fk_import_supplier FOREIGN KEY (supplier_id)
    REFERENCES public.master_suppliers (supplier_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_imports_supplier
    ON public.inventory_imports(supplier_id);


ALTER TABLE IF EXISTS public.inventory_stocks
    ADD CONSTRAINT fk_stock_ingredient FOREIGN KEY (ingredient_id)
    REFERENCES public.master_ingredients (ingredient_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_stocks_ingredient
    ON public.inventory_stocks(ingredient_id);


ALTER TABLE IF EXISTS public.inventory_stocks
    ADD CONSTRAINT fk_stock_kitchen FOREIGN KEY (kitchen_id)
    REFERENCES public.master_kitchens (kitchen_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_stocks_kitchen
    ON public.inventory_stocks(kitchen_id);


ALTER TABLE IF EXISTS public.inventory_transactions
    ADD CONSTRAINT fk_transaction_created_by FOREIGN KEY (created_by_user_id)
    REFERENCES public.master_users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.inventory_transactions
    ADD CONSTRAINT fk_transaction_ingredient FOREIGN KEY (ingredient_id)
    REFERENCES public.master_ingredients (ingredient_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_transactions_ingredient
    ON public.inventory_transactions(ingredient_id);


ALTER TABLE IF EXISTS public.inventory_transactions
    ADD CONSTRAINT fk_transaction_kitchen FOREIGN KEY (kitchen_id)
    REFERENCES public.master_kitchens (kitchen_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_transactions_kitchen
    ON public.inventory_transactions(kitchen_id);


ALTER TABLE IF EXISTS public.kitchen_favorite_suppliers
    ADD CONSTRAINT fk_favorite_kitchen FOREIGN KEY (kitchen_id)
    REFERENCES public.master_kitchens (kitchen_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_favorite_kitchen
    ON public.kitchen_favorite_suppliers(kitchen_id);


ALTER TABLE IF EXISTS public.kitchen_favorite_suppliers
    ADD CONSTRAINT fk_favorite_supplier FOREIGN KEY (supplier_id)
    REFERENCES public.master_suppliers (supplier_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_favorite_supplier
    ON public.kitchen_favorite_suppliers(supplier_id);


ALTER TABLE IF EXISTS public.kitchen_favorite_suppliers
    ADD CONSTRAINT fk_favorite_user FOREIGN KEY (created_by_user_id)
    REFERENCES public.master_users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.master_ingredients
    ADD CONSTRAINT fk_ingredient_type FOREIGN KEY (ingredient_type_id)
    REFERENCES public.ingredient_types (ingredient_type_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.user_kitchens
    ADD CONSTRAINT fk_user_kitchens_user FOREIGN KEY (user_id)
    REFERENCES public.master_users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.user_kitchens
    ADD CONSTRAINT fk_user_kitchens_kitchen FOREIGN KEY (kitchen_id)
    REFERENCES public.master_kitchens (kitchen_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.order_details
    ADD CONSTRAINT fk_detail_dish FOREIGN KEY (dish_id)
    REFERENCES public.master_dishes (dish_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_order_details_dish
    ON public.order_details(dish_id);


ALTER TABLE IF EXISTS public.order_details
    ADD CONSTRAINT fk_detail_order FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_order_details_order
    ON public.order_details(order_id);


ALTER TABLE IF EXISTS public.order_ingredient_suppliers
    ADD CONSTRAINT fk_ois_ingredient FOREIGN KEY (ingredient_id)
    REFERENCES public.master_ingredients (ingredient_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_ois_ingredient
    ON public.order_ingredient_suppliers(ingredient_id);


ALTER TABLE IF EXISTS public.order_ingredient_suppliers
    ADD CONSTRAINT fk_ois_order FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_ois_order
    ON public.order_ingredient_suppliers(order_id);


ALTER TABLE IF EXISTS public.order_ingredient_suppliers
    ADD CONSTRAINT fk_ois_product FOREIGN KEY (selected_product_id)
    REFERENCES public.supplier_price_list (product_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_ois_product
    ON public.order_ingredient_suppliers(selected_product_id);


ALTER TABLE IF EXISTS public.order_ingredient_suppliers
    ADD CONSTRAINT fk_ois_supplier FOREIGN KEY (selected_supplier_id)
    REFERENCES public.master_suppliers (supplier_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_ois_supplier
    ON public.order_ingredient_suppliers(selected_supplier_id);


ALTER TABLE IF EXISTS public.order_ingredient_suppliers
    ADD CONSTRAINT fk_ois_user FOREIGN KEY (selected_by_user_id)
    REFERENCES public.master_users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.order_ingredients
    ADD CONSTRAINT fk_order_ing_detail FOREIGN KEY (order_detail_id)
    REFERENCES public.order_details (order_detail_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_order_ing_detail
    ON public.order_ingredients(order_detail_id);


ALTER TABLE IF EXISTS public.order_ingredients
    ADD CONSTRAINT fk_order_ing_ingredient FOREIGN KEY (ingredient_id)
    REFERENCES public.master_ingredients (ingredient_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_order_ing_ingredient
    ON public.order_ingredients(ingredient_id);


ALTER TABLE IF EXISTS public.order_supplementary_foods
    ADD CONSTRAINT fk_supp_ingredient FOREIGN KEY (ingredient_id)
    REFERENCES public.master_ingredients (ingredient_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_supplementary_ingredient
    ON public.order_supplementary_foods(ingredient_id);


ALTER TABLE IF EXISTS public.order_supplementary_foods
    ADD CONSTRAINT fk_supp_order FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_supplementary_order
    ON public.order_supplementary_foods(order_id);


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fk_order_kitchen FOREIGN KEY (kitchen_id)
    REFERENCES public.master_kitchens (kitchen_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_orders_kitchen
    ON public.orders(kitchen_id);


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fk_order_user FOREIGN KEY (created_by_user_id)
    REFERENCES public.master_users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.supplier_price_list
    ADD CONSTRAINT fk_price_ingredient FOREIGN KEY (ingredient_id)
    REFERENCES public.master_ingredients (ingredient_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_supplier_price_ingredient
    ON public.supplier_price_list(ingredient_id);


ALTER TABLE IF EXISTS public.supplier_price_list
    ADD CONSTRAINT fk_price_supplier FOREIGN KEY (supplier_id)
    REFERENCES public.master_suppliers (supplier_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_supplier_price_supplier
    ON public.supplier_price_list(supplier_id);

END;