-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.dish_recipe_standards
(
    recipe_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    dish_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ingredient_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    unit character varying(50) COLLATE pg_catalog."default" NOT NULL,
    quantity_per_serving numeric(10, 4) NOT NULL,
    notes text COLLATE pg_catalog."default",
    cost numeric(15, 2),
    updated_by_user_id character varying(50) COLLATE pg_catalog."default",
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT dish_recipe_standards_pkey PRIMARY KEY (recipe_id)
);

CREATE TABLE IF NOT EXISTS public.master_dishes
(
    dish_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    dish_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    cooking_method character varying(100) COLLATE pg_catalog."default",
    category character varying(100) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    active boolean NOT NULL DEFAULT true,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT master_dishes_pkey PRIMARY KEY (dish_id),
    CONSTRAINT master_dishes_dish_name_key UNIQUE (dish_name)
);

CREATE TABLE IF NOT EXISTS public.master_ingredients
(
    ingredient_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ingredient_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    properties character varying(100) COLLATE pg_catalog."default",
    material_group character varying(100) COLLATE pg_catalog."default",
    unit character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT master_ingredients_pkey PRIMARY KEY (ingredient_id),
    CONSTRAINT master_ingredients_ingredient_name_key UNIQUE (ingredient_name)
);

CREATE TABLE IF NOT EXISTS public.master_kitchens
(
    kitchen_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    kitchen_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    address text COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    active boolean NOT NULL DEFAULT true,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT master_kitchens_pkey PRIMARY KEY (kitchen_id)
);

CREATE TABLE IF NOT EXISTS public.master_suppliers
(
    supplier_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    supplier_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    zalo_link text COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    active boolean NOT NULL DEFAULT true,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT master_suppliers_pkey PRIMARY KEY (supplier_id)
);

CREATE TABLE IF NOT EXISTS public.master_users
(
    user_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    user_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(50) COLLATE pg_catalog."default",
    kitchen_id character varying(50) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    active boolean NOT NULL DEFAULT true,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT master_users_pkey PRIMARY KEY (user_id),
    CONSTRAINT master_users_user_name_key UNIQUE (user_name)
);

CREATE TABLE IF NOT EXISTS public.order_details
(
    order_detail_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    order_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    dish_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    portions integer NOT NULL,
    note text COLLATE pg_catalog."default",
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT order_details_pkey PRIMARY KEY (order_detail_id)
);

CREATE TABLE IF NOT EXISTS public.order_ingredients
(
    order_ingredient_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    order_detail_id integer NOT NULL,
    ingredient_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    quantity numeric(15, 4) NOT NULL,
    unit character varying(50) COLLATE pg_catalog."default" NOT NULL,
    standard_per_portion numeric(10, 4),
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT order_ingredients_pkey PRIMARY KEY (order_ingredient_id)
);

CREATE TABLE IF NOT EXISTS public.order_supplementary_foods
(
    supplementary_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    order_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ingredient_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    quantity numeric(15, 4) NOT NULL,
    unit character varying(50) COLLATE pg_catalog."default" NOT NULL,
    standard_per_portion numeric(10, 4),
    portions integer,
    note text COLLATE pg_catalog."default",
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT order_supplementary_foods_pkey PRIMARY KEY (supplementary_id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    kitchen_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    order_date date NOT NULL,
    note text COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Pending'::character varying,
    created_by_user_id character varying(50) COLLATE pg_catalog."default",
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    order_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.supplier_price_list
(
    product_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    product_name character varying(255) COLLATE pg_catalog."default",
    ingredient_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    classification character varying(100) COLLATE pg_catalog."default",
    supplier_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    manufacturer_name character varying(255) COLLATE pg_catalog."default",
    unit character varying(50) COLLATE pg_catalog."default",
    specification character varying(100) COLLATE pg_catalog."default",
    unit_price numeric(15, 2) NOT NULL,
    price_per_item numeric(15, 2),
    effective_from timestamp without time zone,
    effective_to timestamp without time zone,
    active boolean NOT NULL DEFAULT true,
    new_buying_price numeric(15, 2),
    promotion character(1) COLLATE pg_catalog."default",
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT supplier_price_list_pkey PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.supplier_request_details
(
    request_detail_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    request_id integer NOT NULL,
    ingredient_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    quantity numeric(15, 4) NOT NULL,
    unit character varying(50) COLLATE pg_catalog."default" NOT NULL,
    unit_price numeric(15, 2) NOT NULL,
    total_price numeric(15, 2) GENERATED ALWAYS AS ((quantity * unit_price)) STORED,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT supplier_request_details_pkey PRIMARY KEY (request_detail_id)
);

CREATE TABLE IF NOT EXISTS public.supplier_requests
(
    request_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    order_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    supplier_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Pending'::character varying,
    created_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT supplier_requests_pkey PRIMARY KEY (request_id)
);

ALTER TABLE IF EXISTS public.dish_recipe_standards
    ADD CONSTRAINT fk_recipe_dish FOREIGN KEY (dish_id)
    REFERENCES public.master_dishes (dish_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_recipe_dish
    ON public.dish_recipe_standards(dish_id);


ALTER TABLE IF EXISTS public.dish_recipe_standards
    ADD CONSTRAINT fk_recipe_ingredient FOREIGN KEY (ingredient_id)
    REFERENCES public.master_ingredients (ingredient_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_recipe_ingredient
    ON public.dish_recipe_standards(ingredient_id);


ALTER TABLE IF EXISTS public.dish_recipe_standards
    ADD CONSTRAINT fk_recipe_user FOREIGN KEY (updated_by_user_id)
    REFERENCES public.master_users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.master_users
    ADD CONSTRAINT fk_users_kitchen FOREIGN KEY (kitchen_id)
    REFERENCES public.master_kitchens (kitchen_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.order_details
    ADD CONSTRAINT fk_detail_dish FOREIGN KEY (dish_id)
    REFERENCES public.master_dishes (dish_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.order_details
    ADD CONSTRAINT fk_detail_order FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_order_details_order
    ON public.order_details(order_id);


ALTER TABLE IF EXISTS public.order_ingredients
    ADD CONSTRAINT fk_order_ing_detail FOREIGN KEY (order_detail_id)
    REFERENCES public.order_details (order_detail_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_order_ing_detail
    ON public.order_ingredients(order_detail_id);


ALTER TABLE IF EXISTS public.order_ingredients
    ADD CONSTRAINT fk_order_ing_ingredient FOREIGN KEY (ingredient_id)
    REFERENCES public.master_ingredients (ingredient_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.order_supplementary_foods
    ADD CONSTRAINT fk_supp_ingredient FOREIGN KEY (ingredient_id)
    REFERENCES public.master_ingredients (ingredient_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.order_supplementary_foods
    ADD CONSTRAINT fk_supp_order FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_supplementary_order
    ON public.order_supplementary_foods(order_id);


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fk_order_kitchen FOREIGN KEY (kitchen_id)
    REFERENCES public.master_kitchens (kitchen_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_orders_kitchen
    ON public.orders(kitchen_id);


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fk_order_user FOREIGN KEY (created_by_user_id)
    REFERENCES public.master_users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.supplier_price_list
    ADD CONSTRAINT fk_price_ingredient FOREIGN KEY (ingredient_id)
    REFERENCES public.master_ingredients (ingredient_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_supplier_price_ingredient
    ON public.supplier_price_list(ingredient_id);


ALTER TABLE IF EXISTS public.supplier_price_list
    ADD CONSTRAINT fk_price_supplier FOREIGN KEY (supplier_id)
    REFERENCES public.master_suppliers (supplier_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_supplier_price_supplier
    ON public.supplier_price_list(supplier_id);


ALTER TABLE IF EXISTS public.supplier_request_details
    ADD CONSTRAINT fk_req_detail_ingredient FOREIGN KEY (ingredient_id)
    REFERENCES public.master_ingredients (ingredient_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.supplier_request_details
    ADD CONSTRAINT fk_req_detail_request FOREIGN KEY (request_id)
    REFERENCES public.supplier_requests (request_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.supplier_requests
    ADD CONSTRAINT fk_req_order FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_supplier_requests_order
    ON public.supplier_requests(order_id);


ALTER TABLE IF EXISTS public.supplier_requests
    ADD CONSTRAINT fk_req_supplier FOREIGN KEY (supplier_id)
    REFERENCES public.master_suppliers (supplier_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_supplier_requests_supplier
    ON public.supplier_requests(supplier_id);


-- Ensure no duplicate supplier request per (order_id, supplier_id)
ALTER TABLE IF EXISTS public.supplier_requests
    ADD CONSTRAINT uq_supplier_requests_order_supplier UNIQUE (order_id, supplier_id);

-- Ensure no duplicate detail per (request_id, ingredient_id)
ALTER TABLE IF EXISTS public.supplier_request_details
    ADD CONSTRAINT uq_supplier_request_details_req_ing UNIQUE (request_id, ingredient_id);

END;